AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Moodel Tenant Api Assets

Parameters:

  DNSName:
    Type: String
    Description: Name of Moodle API route 53 entry to use for target

  HostedZoneName:
    Type: String
    Description: Name of existing route 53 hosted zone name


Resources:

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName:
        Ref: DNSName

  DomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref Certificate
      DomainName: !Ref DNSName

  LambdaDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName:
        Ref: HostedZoneName
      Comment: Zone apex alias targeted to ApiGateway
      RecordSets:
      - Name:
          !Join ["", [Ref: DNSName, "."]]
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # This is hardcoded for all CloudFormation templates
          DNSName: !GetAtt DomainName.DistributionDomainName

  #API Gateway definition
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Latest
      DefinitionBody:
        swagger: 2.0
        info:
          title: !Ref AWS::StackName
        paths:
          "/moodle/stacks":
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetHandler.Arn}:${!stageVariables.env}/invocations
              responses: {}
  #todo- this needs to be cleaned up to "least priviledge"
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"
  # Application assets
  GetHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.moodle.tenant.PostMoodleTenantHandler
      FunctionName: GetHandler
      MemorySize: 512
      Runtime: java8
      CodeUri: build/distributions/MoodleTenantlambda.zip
      Environment:
        Variables:
          DUMMY: Value
      Role: !GetAtt LambdaRole.Arn
      Events:
        PostResource:
          Type: Api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /moodle/tenants
            Method: post

  HandlerVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName:
        Ref: GetHandler
      Description: Most recent published version

Outputs:
  Certificate:
    Value: !Ref Certificate

  DemoApiGatewayRef:
    Value: !Ref APIGateway

  GetHandlerArn:
    Value: !GetAtt GetHandler.Arn
    Export:
      Name: GetHandlerArn

  HandlerVersion:
    Value: !GetAtt HandlerVersion.Version
    Export:
      Name: HandlerVersion